### ISSUE TITLE
Any active HairInstance crash builds (fix inside)

### ISSUE THREAD

**Issue by schemaxxx** [Unity-Technologies/com.unity.demoteam.hair#107]
Hiya,

After updating unity and the hair package from a very early version, all my builds were crashing (on both latest 2023 version and Unity 6).

Unity 6 was able to catch a better stack trace indicating that the IndexBuffer for X-Lines is null.
I was able to trace down the issue to mesh generation, specifically 

**HairTopologyCache.cs:88**

The line

`mesh.UploadMeshData(markNoLongerReadable: true);`

sets the mesh to non-readable, which will cause the IndexBuffer to not be available in builds, while they are still there in the editor. It crashes any build below Unity 6, as GetIndexBuffer() doesn't handle the error before that (though in Unity6 the renderpipeline crashes out as well, but not a hard crash, just an empty screen)

The solution is to simply change the line to 

`mesh.UploadMeshData(markNoLongerReadable: false);`

I'm pretty sure this issue affects all platforms.

cheers,
shma

**Comment by fuglsang** [comment]
Thanks!

**Comment by schemaxxx** [comment]
You are welcome. 

I wonder why the reference to the graphics buffers becomes null when the mesh is no longer readable, as this should only free up memory of the RAM copy of the mesh.
So fetching the graphics buffer of the the mesh in VRAM should still always be possible, no matter if the mesh is readable or not.


This is also relevant because I had implemented my own skinning and blend shape system, which also only works on readable meshes.

I'm not sure if this is the intended behavior, because in all of those cases, the readable mesh is a waste of memory.

Would it be possible to submit a ticket or an inquiry to the core graphics team about this? I'm sure a lot of devs would be thankful if they could get rid of the extra copy in RAM while still being able to directly access the graphics buffer.
