### ISSUE TITLE
'HairRenderer' could not be found in 2023.1.0a7 (HDRP)

### ISSUE THREAD

**Issue by Roland09** [Unity-Technologies/com.unity.demoteam.hair#12]
When you import the project into 2023.1.0a7 (HDRP) these errors show up in the console:

`Library\PackageCache\com.unity.demoteam.hair@7aa92e2cf9\Runtime\HairInstance.cs(84,12): error CS0246: The type or namespace name 'HairRenderer' could not be found (are you missing a using directive or an assembly reference?)`

and

`Library\PackageCache\com.unity.demoteam.hair@7aa92e2cf9\Runtime\HairInstance.cs(190,11): error CS0246: The type or namespace name 'HairRendererGroup' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by bacimen** [comment]
It looks like the project does not recognize the scripting symbols. Double click on the error, you will see a conditional compilation line like this:
`
#if HAS_PACKAGE_UNITY_HDRP_15
`
Change it with this:
`
#if !HAS_PACKAGE_UNITY_HDRP_15
`
After changing the two errors you mentioned, you should see more errors but do the same thing until the errors are gone.

**Comment by matt-tuatara** [comment]
Same issue here with Unity 2023.1.0a6 It seems that HDRP 15 doesn't include any HairRender and/or HairRendererGroup class.

**Comment by AnneCHPostma** [comment]
> Same issue here with Unity 2023.1.0a6 It seems that HDRP 15 doesn't include any HairRender and/or HairRendererGroup class.

Follow the instructions by @bacimen and it should work.

**Comment by matt-tuatara** [comment]
Thanks for the answer. This should indeed fix the issue by excluding the `HairRenderer` and `HairRendererGroup` variables and references but I would like to try the high quality strands using the upcoming compute-based HDRP hair renderer [ depends on Unity >= 2023.1 ] mentionned in [](https://github.com/Unity-Technologies/com.unity.demoteam.hair)
Does this workaround enables this feature ?
