### ISSUE TITLE
Shader error in 'Hair/Default/HairMaterialDefaultLitSRP' in 2022.1.13f1

### ISSUE THREAD

**Issue by ShockWave2048** [Unity-Technologies/com.unity.demoteam.hair#15]
Shader error in 'Hair/Default/HairMaterialDefaultLitSRP' at /Store/Works/TestHairs00/Library/PackageCache/com.unity.demoteam.hair@7aa92e2cf9/Runtime/HairVertex.hlsl(27) (on d3d11)
Unity 2022.1.13f1
DX11, gtx3090, ryzen 3950
How can i fix this? 
Thanks for answer!
![Screenshot_2](https://user-images.githubusercontent.com/800625/185309176-ee6bf3a1-1b15-4b00-84e4-16d0b8919c42.jpg)

**Comment by wojiuxuihuan** [comment]
It seems to be the 'unity_MatrixPreviousMI' get actived twice, try fix it with this order:
1.[Embeded](https://docs.unity3d.com/Manual/upm-embed.html#embed-cached) 'com.unity.demoteam.hair' package;
2.Open 'HairVertex.hlsl' and comment line 26~28:
```
//#ifndef UNITY_SHADER_VARIABLES_INCLUDED
//float4x4 unity_MatrixPreviousMI;
//#endif

#ifndef UNITY_PREV_MATRIX_I_M
#define UNITY_PREV_MATRIX_I_M unity_MatrixPreviousMI
#endif
```
3.The problem will solved (Temporarily).

**Comment by Esjona** [comment]
Also getting this - please solve ASAP as we shouldnt have to constantly fix package errors like this for something being advertised on youtube by unity
