### ISSUE TITLE
macOS Monterey. Unity 2021.3.8f1. Shaders errors when open demo project scene. No hair rendered.

### ISSUE THREAD

**Issue by s0501007** [Unity-Technologies/com.unity.demoteam.hair#16]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/3153408/185546391-1a091a8b-ab27-4f1c-add3-2c19d35fd9f6.png">

**Comment by thecosmicstudios** [comment]
Catalina as well

**Comment by sullysbrain** [comment]
Confirmed in Monterey 12.3.1 (21E258) as well, up to Unity 2022.2.0b7.2913
