### ISSUE TITLE
Compatiblity issues with entities 1.0.0.pre44

### ISSUE THREAD

**Issue by BrundleThwaite** [Unity-Technologies/com.unity.demoteam.hair#45]
When updating entities to the new version (1.0.0.pre44) I get the following error:

Library\PackageCache\com.unity.demoteam.hair@8ad3d098ef\Runtime\HairInstance.cs(820,44): error CS0246: The type or namespace name 'UnsafeMultiHashMap<,>' could not be found (are you missing a using directive or an assembly reference?)

![image](https://user-images.githubusercontent.com/18170954/221438180-56909a33-4730-43a5-8080-66567e4b014e.png)

![image](https://user-images.githubusercontent.com/18170954/221438195-8a4511d6-3ccf-4551-95fa-c78ad8839ba3.png)

**Comment by fuglsang** [comment]
Thanks for reporting. Fix incoming.
