### ISSUE TITLE
Hair "explodes" when I add a material

### ISSUE THREAD

**Issue by MarcTeuberDE** [Unity-Technologies/com.unity.demoteam.hair#53]
When I activate "Material" for the strands and add a material in the slot, the hair transform in these linear random lines. 
![image](https://user-images.githubusercontent.com/75268605/224695661-98e2bbc5-162b-4a57-8227-e11f4575775d.png)

This also happens when I hit undo sometimes and seems to only go away, when I delete and recreate the whole hair asset.
How can I fix this?

**Comment by qlee01** [comment]
Do you have a material with a proper shader graph, which connects vertex positions and normals from the Hair subgraph? You cannot use "any" material for the hair, you need to prepare one with a special shader graph.

**Comment by MarcTeuberDE** [comment]
Yes, thank you! I figured it out now. It works with the HairVertex inputs
