### ISSUE TITLE
angular velocity update in code?

### ISSUE THREAD

**Issue by dokipen3d** [Unity-Technologies/com.unity.demoteam.hair#59]
Hi

I'm trying to find where the angular velocity is stored and updated in the code (from "Position and Orientation Based Cosserat Rods"). Can someone point me in the right direction? Or does this implementation skip that update?

**Comment by fuglsang** [comment]
Hi there. This implementation does not store the orientation of segments -- orientation is inferred, with implied acceptance that the input orientation of each segment (in each iteration) is always a rotation minimizing frame constructed from the root of the strand. The primary reason for this is that we want to conserve bandwidth.

More information can be found in the slides from this talk: https://advances.realtimerendering.com/s2022/index.html#Enemies
