### ISSUE TITLE
Inquiry about VisionPro Device Compatibility with Unity's Hair System

### ISSUE THREAD

**Issue by holdmypanda** [Unity-Technologies/com.unity.demoteam.hair#84]
Dear Unity Hair Team,

My question is regarding the compatibility of your hair system with the VisionPro device. I would like to know if your hair system supports this device for generating and rendering hair assets. This information is crucial for my project as I plan to use the VisionPro device in my workflow.

best

**Comment by khungnguyen** [comment]
I have same question. Does it support Vision pro?

**Comment by holdmypanda** [comment]
> I have same question. Does it support Vision pro?

nope it doesn't work. cause the demo only works in dx api.
