### ISSUE TITLE
After importing this package, it prompts "Invalid worldAABB. Object is too large or too far away from the origin." and a suggestion.

### ISSUE THREAD

**Issue by YeZeLinerr** [Unity-Technologies/com.unity.demoteam.hair#87]
Unity Version: 2022.3.28f1

Steps to Reproduce:

1, Import the package using git link.
2, Import the sample in the package manager.
3, Find that no hair is displayed in the sample scene.
4, Build strand groups.
5, Run or disable+enable the Hair Instance.
6, Error occurs:
Invalid worldAABB. Object is too large or too far away from the origin.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Unity.DemoTeam.Hair.HairInstance:DispatchUpdate () (at ./Library/PackageCache/com.unity.demoteam.hair@be2abe0ac1/Runtime/HairInstance.cs:1138)
Unity.DemoTeam.Hair.HairInstance:HandlePrerequisite () (at ./Library/PackageCache/com.unity.demoteam.hair@be2abe0ac1/Runtime/HairInstance.cs:675)
Unity.DemoTeam.Hair.HairInstance:LateUpdate () (at ./Library/PackageCache/com.unity.demoteam.hair@be2abe0ac1/Runtime/HairInstance.cs:240)

**I imported and runned this package correctly not long ago. Could recent commits have caused this error?**

Additionally, I have a suggestion. It would be great if we could use Alembic curves as guide lines to generate more curves for hair strands at runtime. Importing complete hair curves leads to excessively large .asset files, which makes the game too large.

![1](https://github.com/Unity-Technologies/com.unity.demoteam.hair/assets/53008297/21e3fb89-903f-4049-90ec-4bf999dd3d3c)

**Comment by fuglsang** [comment]
Thanks for the repro steps -- that definitely looks like a regression.

**Comment by fuglsang** [comment]
Fixed the bug, feature request floated to separate issue #89.
